/**
 * Ontology Template Service
 * Provides ontology templates and industry-specific ontologies
 */

const owlOntologyService = require('./owlOntologyService');

class OntologyTemplateService {
  /**
   * Initialize the service
   */
  async initialize() {
    return { success: true };
  }

  /**
   * Get all available ontology templates
   */
  async getAllTemplates(options = {}) {
    const { tenantId, workspaceId } = options;
    return await owlOntologyService.listOntologies(tenantId, workspaceId);
  }

  /**
   * Get available industries/domains
   */
  async getAvailableIndustries(options = {}) {
    return [
      { id: 'resume', name: 'Resume/CV Processing', description: 'Human resources and recruitment' },
      { id: 'legal-contract', name: 'Legal Contracts', description: 'Legal document processing' },
      { id: 'banking', name: 'Banking & Finance', description: 'Financial services domain' },
      { id: 'aml', name: 'Anti-Money Laundering', description: 'AML compliance and monitoring' },
      { id: 'general', name: 'General Purpose', description: 'Generic ontology template' }
    ];
  }

  /**
   * Get template by industry
   */
  async getTemplateByIndustry(industry, options = {}) {
    const { tenantId, workspaceId } = options;
    return await owlOntologyService.getOntology(tenantId, workspaceId, industry);
  }

  /**
   * Get template for extraction (converts OWL structure to extraction format)
   */
  getTemplate(templateId = 'auto') {
    if (templateId === 'auto') {
      // Return auto-generated template (no constraints)
      return {
        isAutoGenerated: true,
        conceptTypes: [],
        predicates: []
      };
    }

    // For specific ontologies, would need to convert OWL structure
    // This is a simplified version - in practice would query GraphDB
    const templates = {
      'resume': {
        conceptTypes: ['Person', 'Company', 'Skill', 'Education', 'Experience'],
        predicates: ['WORKS_AT', 'HAS_SKILL', 'STUDIED_AT', 'HAS_EXPERIENCE'],
        isAutoGenerated: false
      },
      'legal-contract': {
        conceptTypes: ['Party', 'Contract', 'Obligation', 'Term', 'Payment'],
        predicates: ['PARTY_TO', 'HAS_OBLIGATION', 'GOVERNED_BY', 'REQUIRES_PAYMENT'],
        isAutoGenerated: false
      },
      'banking': {
        conceptTypes: ['Customer', 'Account', 'Transaction', 'Product', 'Branch'],
        predicates: ['OWNS_ACCOUNT', 'MAKES_TRANSACTION', 'OFFERS_PRODUCT'],
        isAutoGenerated: false
      }
    };

    return templates[templateId] || templates['auto'];
  }
}

module.exports = new OntologyTemplateService();
