/**
 * OntologyList Component
 * Shows workspace-specific ontologies with option to browse library
 */

const OntologyList = ({
  ontologies,
  selectedOntology,
  loading,
  filter,
  onFilterChange,
  onSelectOntology,
  onCreateNew,
  onBrowseLibrary,
  onGenerate,
  onDeleteOntology
}) => {
  // Show only workspace ontologies (not global)
  const workspaceOntologies = ontologies.filter(ont => ont.scope === 'workspace');

  // Filter ontologies
  const filteredOntologies = workspaceOntologies.filter(ont => {
    if (filter === 'predefined') return false; // No predefined in workspace
    if (filter === 'custom') return ont.isCustom || ont.scope === 'workspace';
    return true;
  });

  // Get icon for ontology type
  const getIcon = (ont) => {
    if (ont.forked_from) return '🔀';
    if (ont.isAutoGenerated) return '🤖';
    if (ont.isCustom) return '✨';
    if (ont.industry === 'banking') return '🏦';
    if (ont.industry === 'aml') return '🔍';
    return '📋';
  };

  // Get class count
  const getClassCount = (ont) => {
    return ont.entityTypes?.length || 
           ont.originalEntityTypes?.length || 
           ont.nodeTypes?.length || 
           ont.classes?.length || 0;
  };

  // Get relationship count (ObjectProperties only)
  const getRelationCount = (ont) => {
    return ont.relationships?.length || 0;
  };

  // Handle delete with confirmation
  const handleDelete = (e, ont) => {
    e.stopPropagation(); // Prevent selecting the ontology
    if (!onDeleteOntology) return;
    if (window.confirm(`Are you sure you want to delete "${ont.name}"? This action cannot be undone.`)) {
      onDeleteOntology(ont);
    }
  };

  return (
    <div className="op-sidebar">
      {/* Header with Browse Library Button */}
      <div className="op-sidebar-header">
        <h3>My Ontologies</h3>
        {onBrowseLibrary && <button 
          className="op-browse-btn" 
          onClick={onBrowseLibrary}
          title="Browse ontology library"
        >
          📚 Library
        </button>}
      </div>

      {/* Filter Tabs */}
      <div className="op-filter-tabs">
        <button 
          className={`filter-tab ${filter === 'all' ? 'active' : ''}`}
          onClick={() => onFilterChange('all')}
        >
          All ({workspaceOntologies.length})
        </button>
        <button 
          className={`filter-tab ${filter === 'custom' ? 'active' : ''}`}
          onClick={() => onFilterChange('custom')}
        >
          Custom ({workspaceOntologies.filter(o => o.isCustom || o.scope === 'workspace').length})
        </button>
      </div>

      {/* Ontology List */}
      <div className="op-list">
        {loading ? (
          <div className="op-loading">
            <span className="loading-spinner"></span>
            Loading ontologies...
          </div>
        ) : filteredOntologies.length === 0 ? (
          <div className="op-empty">
            <p>No ontologies in this workspace</p>
            <p className="op-empty-hint">
              Click "📚 Library" to browse and add ontologies
            </p>
          </div>
        ) : (
          filteredOntologies.map(ont => (
            <div 
              key={ont.id}
              className={`op-list-item ${selectedOntology?.id === ont.id ? 'selected' : ''} ${ont.isCustom ? 'custom' : ''}`}
              onClick={() => onSelectOntology(ont)}
            >
              <div className="op-item-icon">
                {getIcon(ont)}
              </div>
              <div className="op-item-info">
                <span className="op-item-name">{ont.name}</span>
                <div className="op-item-meta">
                  <span>{getClassCount(ont)} classes</span>
                  <span>•</span>
                  <span>{ont.relationships?.length || 0} relations</span>
                  {ont.forked_from && (
                    <span className="op-item-badge forked">Forked</span>
                  )}
                  {ont.isAutoGenerated && (
                    <span className="op-item-badge generated">AI</span>
                  )}
                </div>
              </div>
              <div className="op-item-actions">
                {onDeleteOntology && <button 
                  className="op-delete-btn"
                  onClick={(e) => handleDelete(e, ont)}
                  title="Delete ontology"
                >
                  🗑️
                </button>}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Action Buttons */}
      <div className="op-action-buttons">
        {onGenerate && <button className="op-generate-btn" onClick={onGenerate}>
          🧠 Generate with AI
        </button>}
        {onCreateNew && <button className="op-create-btn" onClick={onCreateNew}>
          + Create Manually
        </button>}
      </div>
    </div>
  );
};

export default OntologyList;
